version: '3.6'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181  
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"  # Opcional, evita creación automática de topics
      KAFKA_DELETE_TOPIC_ENABLE: "true"        # Opcional, permite borrar topics
      ZOOKEEPER_SECURE_CLIENT_PORT: "2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
volumes:
  kafka-data:  # Opcional, volumen para datos persistentes